on:
  port: 8888
  address: 0.0.0.0

admin:
  port: 0
  address: 0.0.0.0

app:
  domain: ''
  brand: App
  search: false
  navbar: true
  fluid: false
  cdn: auto # in DEV mode is false, in PRODUCTION is true
  contextPath: /
  home: /
  menu: {}
  segments:
    admin:
      contextPath: /_
      home: /_
      brand: '<i class="fa fa-dashboard"></i> Admin'
      menu:
        Overview: /_
        Application:
          Routes: /_/routes
          Beans: /_/beans
          Configuration: /_/config
          Deploy: /_/deploy
          Terminate / Restart: /_/terminate
        Data:
          Entities: /_/entities
        Details:
          Metrics: /_/metrics
          Classpath: /_/classpath
        JMX:
          Memory pool: /_/jmx/mempool
          JVM Threads: /_/jmx/threads
          Operating system: /_/jmx/os
          Garbage collection: /_/jmx/gc
          Memory: /_/jmx/memory
          Runtime: /_/jmx/runtime
          Classes: /_/jmx/classes
          Compilation: /_/jmx/compilation

users: {}

jobs:
  executor:
    threads: 64
  scheduler:
    threads: 64

hibernate:
  c3p0:
    min_size: 5
    max_size: 100
    timeout: 300
    max_statements: 50
    idle_test_period: 100

oauth:
  google:
    clientId: YOUR_GOOGLE_CLIENT_ID_HERE
    clientSecret: YOUR_GOOGLE_CLIENT_SECRET_HERE

  github:
    clientId: YOUR_GITHUB_CLIENT_ID_HERE
    clientSecret: YOUR_GITHUB_CLIENT_SECRET_HERE

  facebook:
    clientId: YOUR_FACEBOOK_CLIENT_ID_HERE
    clientSecret: YOUR_FACEBOOK_CLIENT_SECRET_HERE

  linkedin:
    clientId: YOUR_LINKEDIN_CLIENT_ID_HERE
    clientSecret: YOUR_LINKEDIN_CLIENT_SECRET_HERE
